// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDWy3GXn2mzd9e2xUaPdmu
// Component: VlLrZivYvDym

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdAvatar } from "@plasmicpkgs/antd5/skinny/registerAvatar";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: tDWy3GXn2mzd9e2xUaPdmu/projectcss
import sty from "./PlasmicNavbarProliga.module.css"; // plasmic-import: VlLrZivYvDym/css

createPlasmicElementProxy;

export type PlasmicNavbarProliga__VariantMembers = {};
export type PlasmicNavbarProliga__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavbarProliga__VariantsArgs;
export const PlasmicNavbarProliga__VariantProps = new Array<VariantPropType>();

export type PlasmicNavbarProliga__ArgsType = {};
type ArgPropType = keyof PlasmicNavbarProliga__ArgsType;
export const PlasmicNavbarProliga__ArgProps = new Array<ArgPropType>();

export type PlasmicNavbarProliga__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  logo?: Flex__<typeof PlasmicImg__>;
  championat?: Flex__<"a"> & Partial<LinkProps>;
  priz?: Flex__<"a"> & Partial<LinkProps>;
  rules?: Flex__<"a"> & Partial<LinkProps>;
  clubs?: Flex__<"a"> & Partial<LinkProps>;
  empty?: Flex__<"div">;
  avatar?: Flex__<typeof AntdAvatar>;
};

export interface DefaultNavbarProligaProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbarProliga__RenderFunc(props: {
  variants: PlasmicNavbarProliga__VariantsArgs;
  args: PlasmicNavbarProliga__ArgsType;
  overrides: PlasmicNavbarProliga__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <PlasmicImg__
          data-plasmic-name={"logo"}
          data-plasmic-override={overrides.logo}
          alt={""}
          className={classNames(sty.logo)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"45px"}
          loading={"lazy"}
          src={{
            src: "/plasmic/proliga/images/group33Png.png",
            fullWidth: 582,
            fullHeight: 766,
            aspectRatio: undefined
          }}
        />

        <PlasmicLink__
          data-plasmic-name={"championat"}
          data-plasmic-override={overrides.championat}
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.championat
          )}
          component={Link}
          href={`/competition`}
          platform={"nextjs"}
        >
          {"CHAMPIONAT"}
        </PlasmicLink__>
        <PlasmicLink__
          data-plasmic-name={"priz"}
          data-plasmic-override={overrides.priz}
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.priz
          )}
          component={Link}
          href={`/`}
          platform={"nextjs"}
        >
          {"PRIZ"}
        </PlasmicLink__>
        <PlasmicLink__
          data-plasmic-name={"rules"}
          data-plasmic-override={overrides.rules}
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.rules
          )}
          component={Link}
          href={`/`}
          platform={"nextjs"}
        >
          {"QOIDA"}
        </PlasmicLink__>
        <PlasmicLink__
          data-plasmic-name={"clubs"}
          data-plasmic-override={overrides.clubs}
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.clubs
          )}
          component={Link}
          href={`/clubs-2/${""}`}
          platform={"nextjs"}
        >
          {"CLUBS"}
        </PlasmicLink__>
        <div
          data-plasmic-name={"empty"}
          data-plasmic-override={overrides.empty}
          className={classNames(projectcss.all, sty.empty)}
        />

        <AntdAvatar
          data-plasmic-name={"avatar"}
          data-plasmic-override={overrides.avatar}
          className={classNames("__wab_instance", sty.avatar)}
          letters={"client"}
        />
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "logo",
    "championat",
    "priz",
    "rules",
    "clubs",
    "empty",
    "avatar"
  ],
  freeBox: [
    "freeBox",
    "logo",
    "championat",
    "priz",
    "rules",
    "clubs",
    "empty",
    "avatar"
  ],
  logo: ["logo"],
  championat: ["championat"],
  priz: ["priz"],
  rules: ["rules"],
  clubs: ["clubs"],
  empty: ["empty"],
  avatar: ["avatar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  logo: typeof PlasmicImg__;
  championat: "a";
  priz: "a";
  rules: "a";
  clubs: "a";
  empty: "div";
  avatar: typeof AntdAvatar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbarProliga__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbarProliga__VariantsArgs;
    args?: PlasmicNavbarProliga__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavbarProliga__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavbarProliga__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavbarProliga__ArgProps,
          internalVariantPropNames: PlasmicNavbarProliga__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbarProliga__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavbarProliga";
  } else {
    func.displayName = `PlasmicNavbarProliga.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbarProliga = Object.assign(
  // Top-level PlasmicNavbarProliga renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    logo: makeNodeComponent("logo"),
    championat: makeNodeComponent("championat"),
    priz: makeNodeComponent("priz"),
    rules: makeNodeComponent("rules"),
    clubs: makeNodeComponent("clubs"),
    empty: makeNodeComponent("empty"),
    avatar: makeNodeComponent("avatar"),

    // Metadata about props expected for PlasmicNavbarProliga
    internalVariantProps: PlasmicNavbarProliga__VariantProps,
    internalArgProps: PlasmicNavbarProliga__ArgProps
  }
);

export default PlasmicNavbarProliga;
/* prettier-ignore-end */
