// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tDWy3GXn2mzd9e2xUaPdmu
// Component: d7-gk_liJIPx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AvatarPlayer from "../../AvatarPlayer"; // plasmic-import: 4QnaRcOLXj0D/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: tDWy3GXn2mzd9e2xUaPdmu/projectcss
import sty from "./PlasmicTeamPlayerCreate.module.css"; // plasmic-import: d7-gk_liJIPx/css

createPlasmicElementProxy;

export type PlasmicTeamPlayerCreate__VariantMembers = {};
export type PlasmicTeamPlayerCreate__VariantsArgs = {};
type VariantPropType = keyof PlasmicTeamPlayerCreate__VariantsArgs;
export const PlasmicTeamPlayerCreate__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTeamPlayerCreate__ArgsType = {};
type ArgPropType = keyof PlasmicTeamPlayerCreate__ArgsType;
export const PlasmicTeamPlayerCreate__ArgProps = new Array<ArgPropType>();

export type PlasmicTeamPlayerCreate__OverridesType = {
  playersTable?: Flex__<"div">;
  goa?: Flex__<"div">;
  def?: Flex__<"div">;
  mid?: Flex__<"div">;
  str?: Flex__<"div">;
};

export interface DefaultTeamPlayerCreateProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTeamPlayerCreate__RenderFunc(props: {
  variants: PlasmicTeamPlayerCreate__VariantsArgs;
  args: PlasmicTeamPlayerCreate__ArgsType;
  overrides: PlasmicTeamPlayerCreate__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"playersTable"}
      data-plasmic-override={overrides.playersTable}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.playersTable
      )}
    >
      <div
        data-plasmic-name={"goa"}
        data-plasmic-override={overrides.goa}
        className={classNames(projectcss.all, sty.goa)}
      >
        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__kJOkr)}
        />
      </div>
      <Stack__
        as={"div"}
        data-plasmic-name={"def"}
        data-plasmic-override={overrides.def}
        hasGap={true}
        className={classNames(projectcss.all, sty.def)}
      >
        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__bgv2L)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__f242G)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__fDjs8)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__sLjG)}
        />
      </Stack__>
      <Stack__
        as={"div"}
        data-plasmic-name={"mid"}
        data-plasmic-override={overrides.mid}
        hasGap={true}
        className={classNames(projectcss.all, sty.mid)}
      >
        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer___0Q93E)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__jj1UF)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__cWDjm)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__yiv5I)}
        />
      </Stack__>
      <Stack__
        as={"div"}
        data-plasmic-name={"str"}
        data-plasmic-override={overrides.str}
        hasGap={true}
        className={classNames(projectcss.all, sty.str)}
      >
        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__broCp)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__dvzTb)}
        />

        <AvatarPlayer
          className={classNames("__wab_instance", sty.avatarPlayer__zHb7X)}
        />
      </Stack__>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  playersTable: ["playersTable", "goa", "def", "mid", "str"],
  goa: ["goa"],
  def: ["def"],
  mid: ["mid"],
  str: ["str"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  playersTable: "div";
  goa: "div";
  def: "div";
  mid: "div";
  str: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTeamPlayerCreate__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTeamPlayerCreate__VariantsArgs;
    args?: PlasmicTeamPlayerCreate__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTeamPlayerCreate__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTeamPlayerCreate__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTeamPlayerCreate__ArgProps,
          internalVariantPropNames: PlasmicTeamPlayerCreate__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTeamPlayerCreate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "playersTable") {
    func.displayName = "PlasmicTeamPlayerCreate";
  } else {
    func.displayName = `PlasmicTeamPlayerCreate.${nodeName}`;
  }
  return func;
}

export const PlasmicTeamPlayerCreate = Object.assign(
  // Top-level PlasmicTeamPlayerCreate renders the root element
  makeNodeComponent("playersTable"),
  {
    // Helper components rendering sub-elements
    goa: makeNodeComponent("goa"),
    def: makeNodeComponent("def"),
    mid: makeNodeComponent("mid"),
    str: makeNodeComponent("str"),

    // Metadata about props expected for PlasmicTeamPlayerCreate
    internalVariantProps: PlasmicTeamPlayerCreate__VariantProps,
    internalArgProps: PlasmicTeamPlayerCreate__ArgProps
  }
);

export default PlasmicTeamPlayerCreate;
/* prettier-ignore-end */
